// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacMtgPlanner.Models;
using System;

namespace SacMtgPlanner.Migrations
{
    [DbContext(typeof(SacMtgPlannerContext))]
    [Migration("20180410170542_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacMtgPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CloseHymn");

                    b.Property<string>("ClosePrayer");

                    b.Property<string>("Conducting");

                    b.Property<string>("FirstSpeaker");

                    b.Property<string>("OpenHymn");

                    b.Property<string>("OpenPrayer");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("SacHymn");

                    b.Property<string>("SecondSpeaker");

                    b.Property<string>("Subject");

                    b.Property<string>("YouthSpeaker");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
